version: "3.8"
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass Yqsz071102
    volumes:
      - ./data/redis:/data
  psql:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD:Yqsz071102'